# Generated by Django 5.0.4 on 2024-05-10 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSchedules',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('days', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_no', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='scheduleId',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='courseId',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='studentId',
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('instructor', models.CharField(default='', max_length=30)),
                ('capacity', models.IntegerField(default=0)),
                ('prerequisites', models.ManyToManyField(related_name='related_to', through='webapp.CoursePrerequisite', to='webapp.courses')),
                ('schedule_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.courseschedules')),
            ],
        ),
        migrations.AddField(
            model_name='courseprerequisite',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_course', to='webapp.courses'),
        ),
        migrations.AddField(
            model_name='courseprerequisite',
            name='prerequisite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_course', to='webapp.courses'),
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='studentsReg',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.courses')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.students')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseSchedule',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentRegistration',
        ),
    ]

